% ---------------------------- Define symbols -----------------------------
syms z_a z_b z_c z_d z_k
syms wa wb wc wd
syms A_ak A_bk A_ck A_dk
syms A_aa A_bb A_cc A_dd 
syms A_ab A_ac A_ad A_ba A_bc A_bd A_ca A_cb A_cd A_da A_db A_dc
syms hA_ak hA_bk hA_ck hA_dk
syms hA_aa hA_bb hA_cc hA_dd 
syms hA_ab hA_ac hA_ad hA_ba hA_bc hA_bd hA_ca hA_cb hA_cd hA_da hA_db hA_dc
syms calA calB calC calD
syms hcalA hcalB hcalC hcalD

% ----------- Simplify the term related to the operator L_1 ---------------
L1_polynomial = (hA_ck*z_c^2-hA_ak*z_a^2)*(z_d-z_b)*(z_c-z_b)*(z_d-z_a)...
              + (hA_dk*z_d^2-hA_bk*z_b^2)*(z_c-z_a)*(z_c-z_b)*(z_d-z_a)...
              - (hA_ck*z_c^2-hA_bk*z_b^2)*(z_c-z_a)*(z_d-z_b)*(z_d-z_a)...
              - (hA_dk*z_d^2-hA_ak*z_a^2)*(z_c-z_a)*(z_d-z_b)*(z_c-z_b);
% Treatment:
%%% 1 - collect(expand(L1_polynomial), [z_a, z_b, z_c, z_d])
L1_polynomial_collect = ...
     (hA_ak - hA_bk)*z_a^2*z_b^2*z_c + (hA_bk - hA_ak)*z_a^2*z_b^2*z_d ... 
     + (hA_ck - hA_ak)*z_a^2*z_b*z_c^2 + (hA_ak - hA_dk)*z_a^2*z_b*z_d^2 ... 
     + (hA_ak - hA_ck)*z_a^2*z_c^2*z_d + (hA_dk - hA_ak)*z_a^2*z_c*z_d^2 ...
     + (hA_bk - hA_ck)*z_a*z_b^2*z_c^2 + (hA_dk - hA_bk)*z_a*z_b^2*z_d^2 ...
     + (hA_ck - hA_dk)*z_a*z_c^2*z_d^2 + (hA_ck - hA_bk)*z_b^2*z_c^2*z_d ... 
     + (hA_bk - hA_dk)*z_b^2*z_c*z_d^2 + (hA_dk - hA_ck)*z_b*z_c^2*z_d^2;
 
%%% 2 - Regroup manually the 12 terms with same coefficients (A_xk - A_yk) 
L1_polynomial_simplified = (hA_ak - hA_bk)*z_a^2*z_b^2*(z_c - z_d) ...
                         + (hA_ck - hA_ak)*z_a^2*z_c^2*(z_b - z_d) ...
                         + (hA_ak - hA_dk)*z_a^2*z_d^2*(z_b - z_c) ...
                         + (hA_bk - hA_ck)*z_b^2*z_c^2*(z_a - z_d) ...
                         + (hA_dk - hA_bk)*z_b^2*z_d^2*(z_a - z_c) ...
                         + (hA_ck - hA_dk)*z_c^2*z_d^2*(z_a - z_b);
                     
% ---- Sufficient criteria: Regroup and simplify --------------------------
%%% Note that here, omega is included in A
to_simplify = (calA - A_aa)*(z_d - z_b)*(z_c - z_b)*(z_d - z_a)*z_a ...
            + (A_aa - calA)*(z_c - z_a)*(z_d - z_b)*(z_c - z_b)*z_a ...
            - (hA_aa - hcalA)*z_a^2*z_b^2*(z_c - z_d)/z_a ...
            - (hcalA - hA_aa)*z_a^2*z_c^2*(z_b- z_d)/z_a ...
            - (hA_aa - hcalA)*z_a^2*z_d^2*(z_b-z_c)/z_a ...
            + (calB - A_bb)*(z_c - z_a)*(z_c - z_b)*(z_d - z_a)*z_b ...
            + (A_bb - calB)*(z_c - z_a)*(z_d - z_b)*(z_d - z_a)*z_b ...
            - (hcalB - hA_bb)*z_a^2*z_b^2*(z_c - z_d)/z_b ...
            - (hA_bb - hcalB)*z_b^2*z_c^2*(z_a  -  z_d)/z_b ...
            - (hcalB - hA_bb)*z_b^2*z_d^2*(z_a-z_c)/z_b ...
            + (A_cc - calC)*(z_d - z_b)*(z_c - z_b)*(z_d - z_a)*z_c ...
            + (calC - A_cc)*(z_c - z_a)*(z_d - z_b)*(z_d - z_a)*z_c ...
            - (hA_cc - hcalC)*z_a^2*z_c^2*(z_b - z_d)/z_c ...
            - (hcalC - hA_cc)*z_b^2*z_c^2*(z_a  -  z_d)/z_c ...
            - (hA_cc - hcalC)*z_c^2*z_d^2*(z_a - z_b)/z_c ...
            + (A_dd - calD)*(z_c - z_a)*(z_c - z_b)*(z_d - z_a)*z_d ...
            + (calD - A_dd)*(z_c - z_a)*(z_d - z_b)*(z_c - z_b)*z_d ...
            - (hcalD - hA_dd)*z_a^2*z_d^2*(z_b-z_c)/z_d ...
            - (hA_dd - hcalD)*z_b^2*z_d^2*(z_a-z_c)/z_d ...
            - (hcalD - hA_dd)*z_c^2*z_d^2*(z_a - z_b)/z_d;

% collect(expand(to_simplify), [z_a, z_b, z_c, z_d])
simplified_suff = ...
    (A_cc - A_bb + calB - calC + hA_bb - hA_cc - hcalB + hcalC)*z_a^2*z_b*z_c ...
     + (A_bb - A_dd - calB + calD - hA_bb + hA_dd + hcalB - hcalD)*z_a^2*z_b*z_d ...
     + (A_dd - A_cc + calC - calD + hA_cc - hA_dd - hcalC + hcalD)*z_a^2*z_c*z_d ...
     + (A_aa - A_cc - calA + calC - hA_aa + hA_cc + hcalA - hcalC)*z_a*z_b^2*z_c ...
     + (A_dd - A_aa + calA - calD + hA_aa - hA_dd - hcalA + hcalD)*z_a*z_b^2*z_d ...
     + (A_bb - A_aa + calA - calB + hA_aa - hA_bb - hcalA + hcalB)*z_a*z_b*z_c^2 ...
     + (A_aa - A_bb - calA + calB - hA_aa + hA_bb + hcalA - hcalB)*z_a*z_b*z_d^2 ...
     + (A_aa - A_dd - calA + calD - hA_aa + hA_dd + hcalA - hcalD)*z_a*z_c^2*z_d ...
     + (A_cc - A_aa + calA - calC + hA_aa - hA_cc - hcalA + hcalC)*z_a*z_c*z_d^2 ...
     + (A_cc - A_dd - calC + calD - hA_cc + hA_dd + hcalC - hcalD)*z_b^2*z_c*z_d ...
     + (A_dd - A_bb + calB - calD + hA_bb - hA_dd - hcalB + hcalD)*z_b*z_c^2*z_d ...
     + (A_bb - A_cc - calB + calC - hA_bb + hA_cc + hcalB - hcalC)*z_b*z_c*z_d^2;
 

% ---- Necessary criteria: Define terms to regroup and simplify -----------
%%% Note that here, omega is not included in A

%%% 1 - Define auxiliary functions to simplify the notation
f1 = z_k*(z_d - z_b)*(z_c - z_b)*(z_d - z_a);
f1a = z_a*(z_d - z_b)*(z_c - z_b)*(z_d - z_a);
f1b = z_b*(z_d - z_b)*(z_c - z_b)*(z_d - z_a);
f1c = z_c*(z_d - z_b)*(z_c - z_b)*(z_d - z_a);
f1d = z_d*(z_d - z_b)*(z_c - z_b)*(z_d - z_a);

f2 = (z_c - z_a)*(z_c - z_b)*(z_d - z_a)*z_k; 
f2a = (z_c - z_a)*(z_c - z_b)*(z_d - z_a)*z_a;
f2b = (z_c - z_a)*(z_c - z_b)*(z_d - z_a)*z_b;
f2c = (z_c - z_a)*(z_c - z_b)*(z_d - z_a)*z_c;
f2d = (z_c - z_a)*(z_c - z_b)*(z_d - z_a)*z_d; 

f3 = (z_d - z_a)*(z_c - z_a)*(z_d - z_b)*z_k;
f3a = (z_d - z_a)*(z_c - z_a)*(z_d - z_b)*z_a;
f3b = (z_d - z_a)*(z_c - z_a)*(z_d - z_b)*z_b;
f3c = (z_d - z_a)*(z_c - z_a)*(z_d - z_b)*z_c;
f3d = (z_d - z_a)*(z_c - z_a)*(z_d - z_b)*z_d;

f4 =  (z_c - z_b)*(z_c - z_a)*(z_d - z_b)*z_k; 
f4a = (z_c - z_b)*(z_c - z_a)*(z_d - z_b)*z_a; 
f4b = (z_c - z_b)*(z_c - z_a)*(z_d - z_b)*z_b; 
f4c = (z_c - z_b)*(z_c - z_a)*(z_d - z_b)*z_c; 
f4d = (z_c - z_b)*(z_c - z_a)*(z_d - z_b)*z_d; 

g1 =  z_a^2*z_b^2*(z_c -  z_d)/z_k;
g1a = z_a^2*z_b^2*(z_c -  z_d)/z_a;
g1b = z_a^2*z_b^2*(z_c -  z_d)/z_b;
g1c = z_a^2*z_b^2*(z_c -  z_d)/z_c;
g1d = z_a^2*z_b^2*(z_c -  z_d)/z_d;

g2 = (z_b - z_d)*z_a^2*z_c^2/z_k;
g2a = (z_b - z_d)*z_a^2*z_c^2/z_a;
g2b = (z_b - z_d)*z_a^2*z_c^2/z_b;
g2c = (z_b - z_d)*z_a^2*z_c^2/z_c;
g2d = (z_b - z_d)*z_a^2*z_c^2/z_d;

g3 =  (z_b - z_c)*z_a^2*z_d^2/z_k;
g3a = (z_b - z_c)*z_a^2*z_d^2/z_a;
g3b = (z_b - z_c)*z_a^2*z_d^2/z_b;
g3c = (z_b - z_c)*z_a^2*z_d^2/z_c;
g3d = (z_b - z_c)*z_a^2*z_d^2/z_d;

g4 =  (z_a - z_d)*z_b^2*z_c^2/z_k;
g4a = (z_a - z_d)*z_b^2*z_c^2/z_a;
g4b = (z_a - z_d)*z_b^2*z_c^2/z_b;
g4c = (z_a - z_d)*z_b^2*z_c^2/z_c;
g4d = (z_a - z_d)*z_b^2*z_c^2/z_d;

g5 =  (z_a - z_c)*z_b^2*z_d^2/z_k;
g5a = (z_a - z_c)*z_b^2*z_d^2/z_a; 
g5b = (z_a - z_c)*z_b^2*z_d^2/z_b;
g5c = (z_a - z_c)*z_b^2*z_d^2/z_c;
g5d = (z_a - z_c)*z_b^2*z_d^2/z_d;

g6 =  z_c^2*z_d^2*(z_a  - z_b)/z_k;
g6a = z_c^2*z_d^2*(z_a  - z_b)/z_a;
g6b = z_c^2*z_d^2*(z_a  - z_b)/z_b;
g6c = z_c^2*z_d^2*(z_a  - z_b)/z_c;
g6d = z_c^2*z_d^2*(z_a  - z_b)/z_d;
 
Lm1_term_k = (A_ck - A_ak)*f1 + (A_dk - A_bk)*f2 ...
              + (A_bk - A_ck)*f3 + (A_ak - A_dk)*f4;


L1_term_k = (hA_ak - hA_bk)*g1 + (hA_ck - hA_ak)*g2 ...
          + (hA_ak - hA_dk)*g3 + (hA_bk - hA_ck)*g4 ...
          + (hA_dk - hA_bk)*g5 + (hA_ck - hA_dk)*g6;
      
terms_k = Lm1_term_k - L1_term_k;

term_frequency = ...
  1i*((wc - wb)*z_a^2*z_b*z_c + (wb - wd)*z_a^2*z_b*z_d ...
    + (wd - wc)*z_a^2*z_c*z_d + (wa - wc)*z_a*z_b^2*z_c ...
    + (wd - wa)*z_a*z_b^2*z_d + (wb - wa)*z_a*z_b*z_c^2 ...
    + (wa - wb)*z_a*z_b*z_d^2 + (wa - wd)*z_a*z_c^2*z_d ...
    + (wc - wa)*z_a*z_c*z_d^2 + (wc - wd)*z_b^2*z_c*z_d ...
    + (wd - wb)*z_b*z_c^2*z_d + (wb - wc)*z_b*z_c*z_d^2);

term_Lm1_abcd = ...
    (A_ca - A_aa)*f1a + (A_cb - A_ab)*f1b + (A_cc - A_ac)*f1c + (A_cd - A_ad)*f1d ...
    +(A_da - A_ba)*f2a + (A_db - A_bb)*f2b + (A_dc - A_bc)*f2c + (A_dd - A_bd)*f2d ...
    +(A_ba - A_ca)*f3a + (A_bb - A_cb)*f3b + (A_bc - A_cc)*f3c + (A_bd - A_cd)*f3d ...
    +(A_aa - A_da)*f4a + (A_ab - A_db)*f4b + (A_ac - A_dc)*f4c + (A_ad - A_dd)*f4d;

term_L1_abcd = ...
      (hA_aa - hA_ba)*g1a + (hA_ab - hA_bb)*g1b + (hA_ac - hA_bc)*g1c + (hA_ad - hA_bd)*g1d ...
    + (hA_ca - hA_aa)*g2a + (hA_cb - hA_ab)*g2b + (hA_cc - hA_ac)*g2c + (hA_cd - hA_ad)*g2d ...
    + (hA_aa - hA_da)*g3a + (hA_ab - hA_db)*g3b + (hA_ac - hA_dc)*g3c + (hA_ad - hA_dd)*g3d ...
    + (hA_ba - hA_ca)*g4a + (hA_bb - hA_cb)*g4b + (hA_bc - hA_cc)*g4c + (hA_bd - hA_cd)*g4d ...
    + (hA_da - hA_ba)*g5a + (hA_db - hA_bb)*g5b + (hA_dc - hA_bc)*g5c + (hA_dd - hA_bd)*g5d ...
    + (hA_ca - hA_da)*g6a + (hA_cb - hA_db)*g6b + (hA_cc - hA_dc)*g6c + (hA_cd - hA_dd)*g6d;

terms_abcd = term_frequency + term_Lm1_abcd - term_L1_abcd;

% Treatment:
%%% 1 - collect(expand(terms_k), [z_a, z_b, z_c, z_d, z_k]) % 24 terms
terms_k_collect = ...
 ((hA_bk - hA_ak)*z_a^2*z_b^2*z_c + (hA_ak - hA_bk)*z_a^2*z_b^2*z_d ...
+ (hA_ak - hA_ck)*z_a^2*z_b*z_c^2 + (hA_dk - hA_ak)*z_a^2*z_b*z_d^2 ...
+ (A_ck - A_dk)*z_a^2*z_b*z_k^2 + (hA_ck - hA_ak)*z_a^2*z_c^2*z_d ...
+ (hA_ak - hA_dk)*z_a^2*z_c*z_d^2 + (A_dk - A_bk)*z_a^2*z_c*z_k^2 ...
+ (A_bk - A_ck)*z_a^2*z_d*z_k^2 + (hA_ck - hA_bk)*z_a*z_b^2*z_c^2 ...
+ (hA_bk - hA_dk)*z_a*z_b^2*z_d^2 + (A_dk - A_ck)*z_a*z_b^2*z_k^2 ...
+ (hA_dk - hA_ck)*z_a*z_c^2*z_d^2 + (A_bk - A_dk)*z_a*z_c^2*z_k^2 ...
+ (A_ck - A_bk)*z_a*z_d^2*z_k^2 + (hA_bk - hA_ck)*z_b^2*z_c^2*z_d ...
+ (hA_dk - hA_bk)*z_b^2*z_c*z_d^2 + (A_ak - A_dk)*z_b^2*z_c*z_k^2 ...
+ (A_ck - A_ak)*z_b^2*z_d*z_k^2 + (hA_ck - hA_dk)*z_b*z_c^2*z_d^2 ...
+ (A_dk - A_ak)*z_b*z_c^2*z_k^2 + (A_ak - A_ck)*z_b*z_d^2*z_k^2 ...
+ (A_ak - A_bk)*z_c^2*z_d*z_k^2 + (A_bk - A_ak)*z_c*z_d^2*z_k^2)/z_k;
 

%%% 2 - collect(expand(terms_abcd), [z_a, z_b, z_c, z_d, z_k]) % 42 terms
terms_abcd_collect = ...
 ((A_ca - A_da)*z_a^4*z_b^2*z_c*z_d + (A_da - A_ba)*z_a^4*z_b*z_c^2*z_d ...
+ (A_ba - A_ca)*z_a^4*z_b*z_c*z_d^2 + (hA_bd - hA_ad)*z_a^3*z_b^3*z_c^2 ...
+ (A_cb - A_ca + A_da - A_db - hA_ac + hA_ad + hA_bc - hA_bd)*z_a^3*z_b^3*z_c*z_d ...
+ (hA_ac - hA_bc)*z_a^3*z_b^3*z_d^2 + (hA_ad - hA_cd)*z_a^3*z_b^2*z_c^3 ...
+ (A_cc - A_bb + A_db - A_dc - hA_ab + hA_ac + hA_bb - hA_cc - wb*1i + wc*1i)*z_a^3*z_b^2*z_c^2*z_d ...
+ (A_bb - A_cb + A_cd - A_dd + hA_ab - hA_bb - hA_ad + hA_dd + wb*1i - wd*1i)*z_a^3*z_b^2*z_c*z_d^2 ...
+ (hA_dc - hA_ac)*z_a^3*z_b^2*z_d^3 + (A_ba - A_bc - A_da + A_dc + hA_ab - hA_ad - hA_cb + hA_cd)*z_a^3*z_b*z_c^3*z_d ...  
+ (A_bc - A_bd - A_cc + A_dd - hA_ac + hA_ad + hA_cc - hA_dd - wc*1i + wd*1i)*z_a^3*z_b*z_c^2*z_d^2 ...
+ (A_bd - A_ba + A_ca - A_cd - hA_ab + hA_ac + hA_db - hA_dc)*z_a^3*z_b*z_c*z_d^3 ...
+ (hA_cb - hA_ab)*z_a^3*z_c^3*z_d^2 + (hA_ab - hA_db)*z_a^3*z_c^2*z_d^3 ...
+ (A_db - A_cb)*z_a^2*z_b^4*z_c*z_d + (hA_cd - hA_bd)*z_a^2*z_b^3*z_c^3 ...
+ (A_aa - A_cc - A_da + A_dc - hA_aa + hA_ba - hA_bc + hA_cc + wa*1i - wc*1i)*z_a^2*z_b^3*z_c^2*z_d ...
+ (A_ca - A_aa - A_cd + A_dd + hA_aa - hA_ba + hA_bd - hA_dd - wa*1i + wd*1i)*z_a^2*z_b^3*z_c*z_d^2 ...
+ (hA_bc - hA_dc)*z_a^2*z_b^3*z_d^3 + (A_bb - A_aa + A_da - A_db + hA_aa - hA_bb - hA_ca + hA_cb - wa*1i + wb*1i)*z_a^2*z_b^2*z_c^3*z_d...
+ (A_aa - A_bb - A_ca + A_cb - hA_aa + hA_bb + hA_da - hA_db + wa*1i - wb*1i)*z_a^2*z_b^2*z_c*z_d^3     ...
+ (A_bc - A_dc)*z_a^2*z_b*z_c^4*z_d + (A_aa - A_ba + A_bd - A_dd - hA_aa + hA_ca - hA_cd + hA_dd + wa*1i - wd*1i)*z_a^2*z_b*z_c^3*z_d^2 ...
+ (A_ba - A_aa - A_bc + A_cc + hA_aa - hA_da - hA_cc + hA_dc - wa*1i + wc*1i)*z_a^2*z_b*z_c^2*z_d^3 + (A_cd - A_bd)*z_a^2*z_b*z_c*z_d^4 ...
+ (hA_db - hA_cb)*z_a^2*z_c^3*z_d^3 + (A_ab - A_db)*z_a*z_b^4*z_c^2*z_d ...
+ (A_cb - A_ab)*z_a*z_b^4*z_c*z_d^2 + (A_ac - A_ab + A_db - A_dc - hA_ba + hA_ca + hA_bd - hA_cd)*z_a*z_b^3*z_c^3*z_d...
+ (A_ad - A_ac + A_cc - A_dd + hA_bc - hA_bd - hA_cc + hA_dd + wc*1i - wd*1i)*z_a*z_b^3*z_c^2*z_d^2 ...
+ (A_ab - A_ad - A_cb + A_cd + hA_ba - hA_bc - hA_da + hA_dc)*z_a*z_b^3*z_c*z_d^3 ...  
+ (A_dc - A_ac)*z_a*z_b^2*z_c^4*z_d + (A_ab - A_ad - A_bb + A_dd + hA_bb - hA_cb + hA_cd - hA_dd - wb*1i + wd*1i)*z_a*z_b^2*z_c^3*z_d^2 ...
+ (A_ac - A_ab + A_bb - A_cc - hA_bb + hA_cc + hA_db - hA_dc + wb*1i - wc*1i)*z_a*z_b^2*z_c^2*z_d^3 + (A_ad - A_cd)*z_a*z_b^2*z_c*z_d^4 ...
+ (A_ac - A_bc)*z_a*z_b*z_c^4*z_d^2 + (A_ad - A_ac + A_bc - A_bd - hA_ca + hA_cb + hA_da - hA_db)*z_a*z_b*z_c^3*z_d^3 ...
+ (A_bd - A_ad)*z_a*z_b*z_c^2*z_d^4 + (hA_ba - hA_ca)*z_b^3*z_c^3*z_d^2 + (hA_da - hA_ba)*z_b^3*z_c^2*z_d^3 ...
+ (hA_ca - hA_da)*z_b^2*z_c^3*z_d^3)/(z_a*z_b*z_c*z_d);
